# Config used by dashboard client side only

language: "en" # Dashboard UI language
apiBaseUrl: "https://server-bk-xy50.onrender.com/api/v1"
apiWebSocketUrl: "ws://localhost:3001"
developerMode: true
